### ISSUE TITLE
[Bug]: Operator does not perform upgrades on the prometheus-exporter

### ISSUE THREAD

**Issue by JanGrosse** [SolaceProducts/pubsubplus-kubernetes-quickstart#83]
### Bug Description

Hi everyone,
I think I faced a potential bug regarding upgrades towards the prometheus-exporter.
A small testing deployment with the file `initial-deployment.yaml`
```
apiVersion: pubsubplus.solace.com/v1beta1
kind: PubSubPlusEventBroker
metadata:
  name: dev-example
spec:
  developer: true
  monitoring:
    enabled: true
    image:
      repository: solacecommunity/solace-prometheus-exporter
      tag: v1.4.12
```

After the initial deployment I can see my prometheus-exporter running in v1.4.12 as specified in the initial file.
Now, after I edit the tag and increase the version to the next higher one (in this case v1.5.0) and reapply the file
```
apiVersion: pubsubplus.solace.com/v1beta1
kind: PubSubPlusEventBroker
metadata:
  name: dev-example
spec:
  developer: true
  monitoring:
    enabled: true
    image:
      repository: solacecommunity/solace-prometheus-exporter
      tag: v1.5.0
```

Just nothing happens. I thought maybe the reconcilation loop might be longer on the exporter so I gave it a night of sleep, but still in the next morning the version stayed unchanged.

### Expected Behavior

I expected that a increased tag version would cause a upgrade on the prometheus-exporter. I checked in the operational guides for limitations, but did not find one which specified that we can not update the exporter itself ([see here update limitations](https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/main/docs/EventBrokerOperatorUserGuide.md#update-limitations)).

### Steps to Reproduce

See in the bug description.

### Solace Broker version

Latest

### Solace API

none

### Solace API version

none
