### ISSUE TITLE
[Bug]: Specifying image.pullSecrets causes error

### ISSUE THREAD

**Issue by ypismerov-tmx** [SolaceProducts/pubsubplus-kubernetes-quickstart#92]
### Bug Description

An attempt of adding the pullSecrets under spec.image causes the following error:

* spec.monitoring.image.pullSecrets[0]: Invalid value: "string": spec.monitoring.image.pullSecrets[0] in body must be of type object: "string"

~~~
spec:
  image:
     ...
     pullSecrets:
     - reference-to-secret
~~~

At this point it is not possible to pull image from a private registry without resorting to using ServiceAccount based imagePullSecret definition.

### Expected Behavior

The **pullSecrets** parameter with a list of the references to the **kubernetes.io/dockerconfigjson** secrets mentioned [here](https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/main/docs/EventBrokerOperatorUserGuide.md#using-a-private-registry) is expected to be accepted

### Steps to Reproduce

Create kubernetes.io/dockerconfigjson as described [here](https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/main/docs/EventBrokerOperatorUserGuide.md#pulling-images-from-a-private-registry)
Edit PubSubPlusEventBroker manifest and try adding pullSecrets referencing the secret under spec.image as follows:

~~~
spec:
  image:
     ...
     pullSecrets:
     - secret-name
~~~

### Solace Broker version

10.8.1.265

**Comment by LewisKSaint** [comment]
Hello @ypismerov-tmx  thank you for raising this. Currently, we only support sending the `pullSecrets` as `- name: secret-name` . 

Please refer to the OpenAPI spec of the Operator for more details.  

Here is a working example:

```yaml
spec:
  image:
     ...
     pullSecrets:
     - name: secret-name
```

**Comment by ypismerov-tmx** [comment]
Thanks.
In this case the example provided [here](https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/main/docs/EventBrokerOperatorUserGuide.md#container-images)
has to be updated as it references the secret as follows, and itis misleading:
```
  image:
    repository: solace/solace-pubsub-standard
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets:
      - pull-secret
```
